### ISSUE TITLE
mermaid missing text in svg

### ISSUE THREAD

**Issue by dolfijn3000** [mermaid-js/mermaid-cli#112]
**Describe the bug**
i created a simple mmdc file. and when generated to an svg it is missing text.

**To Reproduce**
i made a file called test.mmdc wit this code:

`graph TD
    id1[This is the text in the box]`

then I converted it with this command:
 mmdc -i test.mmdc

it then generated this:
https://imgur.com/a/FmDRxV3

**Expected behavior**
I expected that the text "This is the text in the box" would appear in the box

**Screenshots**
https://imgur.com/a/FmDRxV3

**Desktop (please complete the following information):**

- OS: windows 10
- Browser chrome
- Version89.0.4389.90

**Comment by MindaugasLaganeckas** [comment]
@dolfijn3000 : please, check with Mermaid live editor: https://mermaid-js.github.io/mermaid-live-editor
If you get the same behavior, then please, move your issue to https://github.com/mermaid-js/mermaid, because it is a generic mermaid problem not related to the CLI tool.
I have actually tried your diagram snippet, and the live editor gives a syntax error.

**Comment by merrickluo** [comment]
I can confirm the issue exists with @mermaid-js/mermaid-cli@8.9.2, it seems this problem only exists for graph/flowchart, sequence Diagram seems fine
```
graph TD
id1[This is the text in the box]
```
This produces
screenshot 
![image](https://user-images.githubusercontent.com/1495875/114990214-e192aa80-9eca-11eb-957e-23aee09b1d40.png)

<details>
<summary>generated svg</summary>

```svg
<svg id="mermaid-1618558838626" width="100%" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="54" style="max-width: 212.984375px;" viewBox="0 0 212.984375 54"><style>#mermaid-1618558838626{font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:16px;fill:#333;}#mermaid-1618558838626 .error-icon{fill:#552222;}#mermaid-1618558838626 .error-text{fill:#552222;stroke:#552222;}#mermaid-1618558838626 .edge-thickness-normal{stroke-width:2px;}#mermaid-1618558838626 .edge-thickness-thick{stroke-width:3.5px;}#mermaid-1618558838626 .edge-pattern-solid{stroke-dasharray:0;}#mermaid-1618558838626 .edge-pattern-dashed{stroke-dasharray:3;}#mermaid-1618558838626 .edge-pattern-dotted{stroke-dasharray:2;}#mermaid-1618558838626 .marker{fill:#333333;stroke:#333333;}#mermaid-1618558838626 .marker.cross{stroke:#333333;}#mermaid-1618558838626 svg{font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:16px;}#mermaid-1618558838626 .label{font-family:"trebuchet ms",verdana,arial,sans-serif;color:#333;}#mermaid-1618558838626 .cluster-label text{fill:#333;}#mermaid-1618558838626 .cluster-label span{color:#333;}#mermaid-1618558838626 .label text,#mermaid-1618558838626 span{fill:#333;color:#333;}#mermaid-1618558838626 .node rect,#mermaid-1618558838626 .node circle,#mermaid-1618558838626 .node ellipse,#mermaid-1618558838626 .node polygon,#mermaid-1618558838626 .node path{fill:#ECECFF;stroke:#9370DB;stroke-width:1px;}#mermaid-1618558838626 .node .label{text-align:center;}#mermaid-1618558838626 .node.clickable{cursor:pointer;}#mermaid-1618558838626 .arrowheadPath{fill:#333333;}#mermaid-1618558838626 .edgePath .path{stroke:#333333;stroke-width:1.5px;}#mermaid-1618558838626 .flowchart-link{stroke:#333333;fill:none;}#mermaid-1618558838626 .edgeLabel{background-color:#e8e8e8;text-align:center;}#mermaid-1618558838626 .edgeLabel rect{opacity:0.5;background-color:#e8e8e8;fill:#e8e8e8;}#mermaid-1618558838626 .cluster rect{fill:#ffffde;stroke:#aaaa33;stroke-width:1px;}#mermaid-1618558838626 .cluster text{fill:#333;}#mermaid-1618558838626 .cluster span{color:#333;}#mermaid-1618558838626 div.mermaidTooltip{position:absolute;text-align:center;max-width:200px;padding:2px;font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:12px;background:hsl(80,100%,96.2745098039%);border:1px solid #aaaa33;border-radius:2px;pointer-events:none;z-index:100;}#mermaid-1618558838626:root{--mermaid-font-family:"trebuchet ms",verdana,arial,sans-serif;}#mermaid-1618558838626 flowchart{fill:apa;}</style><g><g class="output"><g class="clusters"></g><g class="edgePaths"></g><g class="edgeLabels"></g><g class="nodes"><g class="node default" id="flowchart-id1-1" transform="translate(106.4921875,27)" style="opacity: 1;"><rect rx="0" ry="0" x="-98.4921875" y="-19" width="196.984375" height="38" class="label-container"></rect><g class="label" transform="translate(0,0)"><g transform="translate(-88.4921875,-9)"><foreignObject width="176.984375" height="18"><div xmlns="http://www.w3.org/1999/xhtml" style="display: inline-block; white-space: nowrap;">This is the text in the box</div></foreignObject></g></g></g></g></g></g></svg>
```

</details>

**Comment by merrickluo** [comment]
Did a little digging, it seems that when using graph, mermaid generated svg is using `foreignObject` to render the text in node, and emacs and some other svg viewer is not handling it well (browser renders it fine).

**Comment by MindaugasLaganeckas** [comment]
@merrickluo : can you provide a sample config file and how to use it together with a mermaid-cli docker? I can include this config file in the docker image and document how to access it if anyone needs it. If the config file does not have side effects, I can set it in use by default for docker.

**Comment by merrickluo** [comment]
@MindaugasLaganeckas the config file I use is like this
```json
{
  "flowchart": {
    "useMaxWidth": false,
    "htmlLabels": false
  }
}
```
only the `htmlLabels` part matters though. I just use it by passing the file to mermaid-cli 
`mmdc -c ~/.config/mermaid/config.json`

**Comment by yevhene** [comment]
Hi. same issue. SVG in browser is ok but in viewer is not.

**Comment by ShaoHao-Chen** [comment]
> 


```
"htmlLabels": false
```
above config can solve text missing issue.
But I face another issue, my connection line is missing.
Is there a way to show the connection line?
![image](https://user-images.githubusercontent.com/81244111/142725228-74dbdef2-fd5c-4d57-8842-7ac689287c53.png)

**Comment by abject** [comment]
I need to use `"htmlLabels": false` config to have text in SVG graphics. However this force a double escaping sequence of special characters.
In fact the following markdown code:
````
```mermaid
   graph TD
      A["&lt;"]
      B["<"]
      A --> B
```
````
provides this SVG picture with the above configuration:
![test_amp-1](https://user-images.githubusercontent.com/1702172/155500175-4fe189ba-44f9-4e37-9aac-473f77c62a3d.svg)
Looking at the SVG code I found that escaped characters are escape two times: `<` became `&amp;lt;` which prevent good rendering.

**Comment by craigmac** [comment]
@[MindaugasLaganeckas](https://github.com/MindaugasLaganeckas) did this ever get document/put anywhere?

**Comment by MindaugasLaganeckas** [comment]
@craigmac : please, create a PR if you think that the documentation can be improved. We have already a section with known issues 👍 Thank you for your help! 😄

**Comment by datalifenyc** [comment]
Potential workarounds:

1. Comments (`%%`) above an abbreviated form of the text.

```html
<div class="mermaid">
  graph TD
    ...
    subgraph Dremio Data Lakehouse
      direction TB
      E1[Data Lake]
      %% Table Format
      F1[Apache Iceberg]
      %% Transactional Catalog
      G1[Project Nessie]
      E1 -->|Managed By| F1
      F1 -->|Versioned By| G1
    end
    ...
</div>
```

2. Use `<br/>` tags, which increases the height rather than the width.

```html
<div class="mermaid">
  graph TD
    ...
    subgraph Dremio Data Lakehouse
      direction TB
      E1[Data Lake]
      F1[<b>Table Format</b>:<br/>Apache Iceberg]
      G1[<b>Transactional Catalog:</b><br/>Project Nessie]
      E1 -->|Managed By| F1
      F1 -->|Versioned By| G1
    end
    ...
</div>
```

Note: _The approach for rendering `.svg` may be different, but hopefully this provides clues to another method for resolving this issue._

**Comment by Amer-Jabar** [comment]
I faced the same issue when rendering mermaid graphs using _mermaid.js_ and this was the fix for me.

### Cause Of Issue
For me the issue arose when having nodes with text that were long - longer than 27 letters. Then the text in the node would disappear. The cause was that the `<g class="label">` tag has a translation of (0, 0) - perhaps some JS logic skips nodes with a text of longer than 27 letters.
![Screenshot 2024-09-16 at 13 25 28](https://github.com/user-attachments/assets/e456d20f-4438-48f4-a230-3a4b35c599bd)

### Quick Fix
Using `htmlLabels: false` fixed the issue by changing the children html tags of the `<g class="label">` to texts and spans. However, the text was still being wrapped.
![Screenshot 2024-09-16 at 13 28 09](https://github.com/user-attachments/assets/65eb8392-0b19-4700-ab78-ab5654add750)

### Another Fix
By adding `wrappingWidth: 1000` to the `mermaid.initialize()` method, I was able to fix the issue without using the `htmlLabels: false` flag:
```
mermaid.initialize({
    startOnLoad: true, flowchart: {
      wrappingWidth: 1000
    }
})
```
![Screenshot 2024-09-16 at 13 31 59](https://github.com/user-attachments/assets/334d6086-34c1-4d77-84b3-820c87b039a6)

The problem is that, a node would still disappear if the text is longer than 1000 letters. **So, you can set it to -1 and it will never be wrapped.**

**Comment by carloskelly13** [comment]
The fix
```
"flowchart": {
    "useMaxWidth": false,
    "htmlLabels": false
  }
```
for the config worked for me in v10, but upgrading to v11 made the text show up again inside the `<foreignObject />`

**Comment by aubertc** [comment]
> I need to use `"htmlLabels": false` config to have text in SVG graphics. However this force a double escaping sequence of special characters. 

I'm not sure I understand this comment.

```
classDiagram 
class IComparable~Shape~{
    <<Interface>>
    +CompareTo(arg : Shape) int*
    }
```

with the following `.mermaid-config.json`

```json
{
    "flowchart": {
        "htmlLabels": "false"
    }
}
```

produces the following:

![cla](https://github.com/user-attachments/assets/d3f9adc4-17ba-436b-acd8-9b52d4df452a)

The same code [produces the expected output](https://www.mermaidchart.com/play?utm_source=mermaid_js&utm_medium=banner_ad&utm_campaign=AIbundle#pako:eNqrVkrOT0lVslJKzkksLnbJTEwvSsxViMkDcxU8nfNzCxKLEpNyUuuCMxILUuuqY_IUgMDGxjOvJLUoLTE51c4OIqQNUZsakq-RWJSuYKUA1qCpkJlXogVRUatUCwBwRCUI) without the `htmlLabels`, but I need it to export to svg correctly: how should I escape the `~` characters to obtain the desired output?

**Comment by rrrodzilla** [comment]
> Did a little digging, it seems that when using graph, mermaid generated svg is using `foreignObject` to render the text in node, and emacs and some other svg viewer is not handling it well (browser renders it fine).
> 
> Update: This can be workaround by adding a custom config file set `htmlLabels` to false.

This worked great for me. Thanks.

**Comment by billwanjohi** [comment]
> Update: But not in the latest version 11.4 ☹️

Can corroborate, this fix works for me up to version 10.9.1, but not any of the 11.x versions

**Comment by SasooXD** [comment]
Unfortunately the problem still persist in later versions, as other pointed out. Is there any work around?

**Comment by aeonik** [comment]
I am on v11.4.2 of mermaid-cli

I had to set the `"htmlLabels": false` in two difference places to get my flow charts to render text using SVG:
```json
{
    "htmlLabels": false,
    "flowchart": {
    "htmlLabels": false
  }
}
```

However I am also still running into the escaping bug. It is unclear to me how I can render a literal `&`. Spaces also seem to be missing.

I checked the raw SVG XML file and found that it has a double `&amp;` in there:
![Image](https://github.com/user-attachments/assets/ffde9633-0f02-434b-8e0c-7babecf2b93d)
```xml
<text y="-10.1" style="">
  <tspan class="text-outer-tspan" x="0" y="-0.1em" dy="1.1em">
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal">Test</tspan>
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal"> Hello</tspan>
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal"> &amp;amp;</tspan>
  </tspan>
  <tspan class="text-outer-tspan" x="0" y="1em" dy="1.1em">
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal">Test2</tspan>
  </tspan>
</text>
```

When I try to escape it like this `\&`
The tag is completely missing:
![Image](https://github.com/user-attachments/assets/6774f53d-c2d9-40a0-901a-53a2b68046b6)
```xml
<text y="-10.1" style="">
  <tspan class="text-outer-tspan" x="0" y="-0.1em" dy="1.1em">
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal">Test</tspan>
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal"> Hello</tspan>
  </tspan>
  <tspan class="text-outer-tspan" x="0" y="1em" dy="1.1em">
    <tspan font-style="normal" class="text-inner-tspan" font-weight="normal">Test2</tspan>
  </tspan>
</text>
```

When I add a literal `&amp;` into the text I get the same double &amp;&amp; which makes me think some pre-processor is pre-escaping the ampersand and not unescaping during write.

Here is an example flowchart with the problem, though it renders fine here...
```mermaid
%%{init: {"htmlLabels": false, "flowchart": {"htmlLabels": false}} }%%
flowchart TD
    %% Zone A
    subgraph Zone_A["Zone A"]
        Node_A1(["Crystal Relay"])
        Node_A2(["Echo Mapper"])
        Node_A3(["Glyph Tracker"])
        Node_A4(["Spiral Scribe"])
        Node_A5(["Wisp Anchor"])
        Node_A6(["Drift Beacon"])
        Node_A7(["Cycle Timer"])
    end

    %% Zone B
    subgraph Zone_B["Zone B"]
        Node_B1(["Phase Sorter"])
        Node_B2(["Quartz Reader"])
        Node_B3(["Pulse Relay"])
        Node_B4(["Mirror Array"])
        Node_B5(["Chorus Node"])
        Node_B6(["Test Hello & Test2"])
        Node_B7(["Signal Bloom"])
    end

    %% Connections
    Node_A1 --> Node_A2
    Node_A1 --> Node_A3
    Node_A3 --> Node_A4
    Node_A5 --> Node_A6
    Node_A7 --> Node_A6
    Node_A3 --> Node_A7

    Node_A6 --> Node_B1
    Node_A6 --> Node_B5
    Node_A4 --> Node_B3

    Node_B3 -->|Suggests| Node_B4
    Node_B1 -->|Routes Queries| Node_B3
    Node_B2 -->|Feeds| Node_B7
    Node_B3 --> Node_B5
    Node_B5 --> Node_B4
    Node_B6 --> Node_B5
    Node_B6 --> Node_B3
```

**Comment by lopeztel** [comment]
This is still a problem in version 11.12.0
I've tried to generate a SVG file using the config file trick mentioned above: `mmdc -c ~/.config/mermaid/config.json -i mermaid_demo.mmd -o mermaid_demo.svg`

which yields output:
```sh
Generating single mermaid chart

Error: splitLineToFitWidth does not support newlines in the line
    at #evaluate (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:388:19)
    at async ExecutionContext.evaluate (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:275:16)
    at async IsolatedWorld.evaluate (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:97:16)
    at async CdpJSHandle.evaluate (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/api/JSHandle.js:146:20)
    at async CdpElementHandle.evaluate (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/api/ElementHandle.js:340:20)
    at async CdpElementHandle.$eval (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/api/ElementHandle.js:494:24)
    at async CdpFrame.$eval (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:450:20)
    at async CdpPage.$eval (file:///var/home/lopeztel/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:450:20)
    at async renderMermaid (file:///var/home/lopeztel/node_modules/@mermaid-js/mermaid-cli/src/index.js:266:22)
    at render (/var/home/lopeztel/node_modules/mermaid/dist/mermaid.js:90727:30)
```
So now no file is even generated.

Invisible text otherwise
