### ISSUE TITLE
8.9.3 docker image appears not to work

### ISSUE THREAD

**Issue by mikewilson-dd** [mermaid-js/mermaid-cli#120]
**Describe the bug**
When using the 8.9.3 docker image, it immediately exits out with what appear to be a Node issue.

```
ls -1 diagrams | xargs -I{} sh -c 'docker run -u $(id -u) -v /local-diagram-path:/diagrams" -v "/local-image-output-path:/images" minlag/mermaid-cli:8.9.3 -i "/diagrams/$0" -o "/images/${0%.*}.png"' {}
/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
    at Interface.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)
    at Interface.emit (node:events:377:35)
    at Interface.close (node:readline:548:8)
    at Socket.onend (node:readline:260:10)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
make: *** [generate-diagrams] Error 123
```

**To Reproduce**

1. Use the mermaid-cli docker image to generate an image based on an `.mmd` file.

**Expected behavior**
An image should be created by mermaid.

**Desktop (please complete the following information):**

- OS: Mac OS X 11.3.1
- Version 8.9.3

**Comment by bentito** [comment]
I concur, we fell back to last working tag. https://github.com/operator-framework/index-mermaid-graph/blob/main/Makefile

**Comment by MindaugasLaganeckas** [comment]
We have release 8.9.3-1, that provides a fix to the error. Please, try it out! :)
