### ISSUE TITLE
Running with Docker/Podman: Permission Denied

### ISSUE THREAD

**Issue by jeschkies** [mermaid-js/mermaid-cli#140]
When I run the Docker image with Docker or Podman I get the following error

```
› podman run -it -v "$(pwd)":/data:z minlag/mermaid-cli -i /data/diagram.mmd
node:fs:582
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open '/data/diagram.mmd.svg'
    at Object.openSync (node:fs:582:3)
    at Object.writeFileSync (node:fs:2143:35)
    at /home/mermaidcli/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:169:10
    at Generator.next (<anonymous>)
    at step (/home/mermaidcli/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:4:191)
    at /home/mermaidcli/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:4:361
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/data/diagram.mmd.svg'
}
```

How can I run the CLI without root?

**Comment by jeschkies** [comment]
It works if the user is switched to root `podman run -it -v "$(pwd)":/data:z -u root minlag/mermaid-cli -i /data/diagram.mmd`.

**Comment by MindaugasLaganeckas** [comment]
I have switched from root to mermaidcli in docker images. But I did not see any problem when running the tests: https://github.com/mermaid-js/mermaid-cli/blob/194060f51e4cf56accf695ab77c886baefb9e7a8/run-tests.sh#L8

Can you try to map data to /home/mermaidcli/data instead and see if that works without specifying root in the cli?

**Comment by jeschkies** [comment]
Thanks for the reply. I get the same issues. What OS are you using?

**Comment by MindaugasLaganeckas** [comment]
I am using ubuntu in my tests: https://github.com/mermaid-js/mermaid-cli/blob/194060f51e4cf56accf695ab77c886baefb9e7a8/.github/workflows/compile-mermaid.yml#L5

**Comment by fconil** [comment]
Had the same issue with docker on Ubuntu, solved using docker -u option with my uid

`docker run -u <user_uid> -it --rm -v "$(pwd)":data minlag/mermaid-cli -i /data/diagram.mmd`

**Comment by chebro** [comment]
@MindaugasLaganeckas i could replicate the issue on ubuntu, docker uses the host file permissions when using bind mounts so the (host) `data` directory doesn't provide write access to the docker (mermaidcli) user.

i see two possible solutions to this (without modifying the dockerfile),
1. pass `-u $UID` at runtime. (as suggested by @fconil )
2. modify the permissions for the `data` directory to `777` that way user groups outside of the host user can have write access to it (but this  is a security risk).
