### ISSUE TITLE
`mmdc` command fails on WSL

### ISSUE THREAD

**Issue by sudhih** [mermaid-js/mermaid-cli#232]
**Evaluation failed: TypeError: Cannot read property 'initialize' of undefined**

When `mmdc -p puppeteer-config.json -i samplecharts.md` run on Windows Subsystem for Linux(WSL), it fails to generate default `.svg` or create `.md` file as described in [here](github.com/mermaid-js/mermaid-cli) Error is as below. 
*Can we run this tool making it to run without trying to open chrome* I assume that's the issue, & in my WSL there's no chrome installed. 

```
/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'initialize' of undefined
    at __puppeteer_evaluation_script__:3:20
    at ExecutionContext._evaluateInternal (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async ElementHandle.evaluate (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:102:16)
    at async ElementHandle.$eval (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:650:24)
```

**Content of `puppteer-config.json`**
```
{
    "args": ["--no-sandbox"]
}
```

**My set up**
1. I followed instruction to install `nvm`, `node` & `npm` from [here](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm)
2. I choose to install `--lts` version
3. installed version looks like
```
➜  node --version
v16.13.2
➜  nvm --version
0.39.0
➜  npm --version
8.1.2
➜  
```
4. install `mermaid-cli` using `npm install mermaid.cli ./node_modules/.bin/mmdc -h`

**To Reproduce**

1. Open `Windows Terminal` and choose installed `wsl` in my case `Ubuntu-20.04`
2. Create input file like: `samplecharts.md` with following content
```
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```
3. create `puppeteer-config.json` with following content
```
{
    "args": ["--no-sandbox"]
}
```
4. run `mmdc -p puppeteer-config.json -i samlcharts.md`, output is, described as above
5. when run without `-p puppteer-config.json` the error is as follows,
```
/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[0126/092416.076463:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x7fda3d494259 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f929e97ae)
#1 0x7fda3d4009e3 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f92955f38)
#2 0x7fda3d411610 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f92966b65)
#3 0x7fda3bafa83b (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f9104fd90)
#4 0x7fda3d3a080c (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f928f5d61)
#5 0x7fda3d39eb09 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f928f405e)
#6 0x7fda3d39ec3d (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f928f4192)
#7 0x7fda3d3fac29 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f9295017e)
#8 0x7fda3d3fa93a (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f9294fe8f)
#9 0x7fda3a42b3e1 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f8f980936)
#10 0x7fda355f70b3 (/usr/lib/x86_64-linux-gnu/libc-2.31.so+0x5555d52f8ab4c608)
#11 0x7fda3a42b22a (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f8f98077f)

Received signal 6
#0 0x7fda3d494259 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f929e97ae)
#1 0x7fda3d4009e3 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f92955f38)
#2 0x7fda3d493e00 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f929e9355)
#3 0x7fda370c23c0 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x5555d52f8c617915)
#4 0x7fda3561618b (/usr/lib/x86_64-linux-gnu/libc-2.31.so+0x5555d52f8ab6b6e0)
#5 0x7fda355f5859 (/usr/lib/x86_64-linux-gnu/libc-2.31.so+0x5555d52f8ab4adae)
#6 0x7fda3d493425 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f929e897a)
#7 0x7fda3d411a37 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f92966f8c)
#8 0x7fda3bafa83b (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f9104fd90)
#9 0x7fda3d3a080c (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f928f5d61)
#10 0x7fda3d39eb09 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f928f405e)
#11 0x7fda3d39ec3d (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f928f4192)
#12 0x7fda3d3fac29 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f9295017e)
#13 0x7fda3d3fa93a (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f9294fe8f)
#14 0x7fda3a42b3e1 (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f8f980936)
#15 0x7fda355f70b3 (/usr/lib/x86_64-linux-gnu/libc-2.31.so+0x5555d52f8ab4c608)
#16 0x7fda3a42b22a (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome+0x5555d52f8f98077f)
  r8: 0000000000000000  r9: 00007fffd54863d0 r10: 0000000000000008 r11: 0000000000000008
 r12: 00007fffd54876a0 r13: 00007fffd5486630 r14: 00007fffd54876b0 r15: aaaaaaaaaaaaaaaa
di: 0000000000000002  si: 00007fffd54863d0  bp: 00007fffd5486620  bx: 00007fda33fa0dc0
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000008  sp: 00007fffd54863d0
  ip: 00007fda3561618b efl: 0000000000000246 cgf: 00000053002b0033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
    at Interface.<anonymous> (/mnt/c/Users/sudhir.hanumanthappa/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Expected behavior**
SVG file generated without trying to open browser. when run `-o` flag, behave as described in 

**Screenshots**

**Desktop:**

- OS: Windows 10(wsl Ubuntu-20.04)

**Comment by MindaugasLaganeckas** [comment]
Chrome is needed unfortunately. You can use our docker image to run mermaid-cli or you can install the missing dependencies in your WSL. You can get inspired from our docker setup: https://github.com/mermaid-js/mermaid-cli/blob/master/install-dependencies.sh

Closing the case, because there is nothing else we can do at the moment.
You are welcome to reopen if you disagree.

**Comment by tsbertalan** [comment]
This helped me, after installing nvm and node per [these instructions](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl):

```bash
sudo apt update
sudo apt install -y libatk-bridge2.0-0 libnss3 libcups2 lib32z1 libxcomposite-dev libxdamage1 libxrandr2 libgbm1 libxkbcommon-x11-0  libpangocairo-1.0-0 libasound2
```
