### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by axaluss** [mermaid-js/mermaid-cli#318]
**Describe the bug**
mmdc crashes with `SyntaxError: Unexpected token`

**To Reproduce**
`$ brew install mermaid-cli`
`$ mmdc -h`

```
$ mmdc
/usr/local/Cellar/mermaid-cli/8.11.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:730
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/mermaid-cli/8.11.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:19:19)
```
 
**Desktop (please complete the following information):**

- OS: Mac OS 12.4

**Comment by MindaugasLaganeckas** [comment]
I suggest to make sure that you are using the latest version of mermaid. We have issues with mac https://github.com/mermaid-js/mermaid-cli/issues/288 My suggestion for you is to use the docker image if you cannot upgrade.

**Comment by MindaugasLaganeckas** [comment]
BTW, we do provide bug fixes only to the newest version of mermaid-cli. Versions such as 8.11.0 will not receive a bugfix.

**Comment by MindaugasLaganeckas** [comment]
Will close this issue because it is about mermaid-cli 8.11.0. We do not provide bugfixes to the released versions of mermaid-cli except for the most recent one.
