### ISSUE TITLE
Error after installation:  TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function

### ISSUE THREAD

**Issue by vkotovv** [mermaid-js/mermaid-cli#35]
Mermaid-cli is not working after install, here is the log:
```
kotov@kotov-office:~/Apps/mermaid-cli$ ./node_modules/.bin/mmdc -h
internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/kotov/Apps/mermaid-cli/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kotov/Apps/mermaid-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:48:39)
```

**To Reproduce**
1. Install it locally via `yarn add @mermaid-js/mermaid-cli`
2. Run it

**My environment:**
 - OS: Ubuntu 20.04

**Installation log:**
```
kotov@kotov-office:~/Apps/mermaid-cli$ yarn add @mermaid-js/mermaid-cli
yarn add v1.16.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.16.0".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
success Saved 60 new dependencies.
info Direct dependencies
└─ @mermaid-js/mermaid-cli@8.7.0
info All dependencies
├─ @mermaid-js/mermaid-cli@8.7.0
├─ @types/color-name@1.1.1
├─ @types/node@14.0.27
├─ @types/yauzl@2.9.1
├─ agent-base@5.1.1
├─ ansi-styles@4.2.1
├─ balanced-match@1.0.0
├─ base64-js@1.3.1
├─ bl@4.0.2
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ buffer@5.6.0
├─ chalk@4.1.0
├─ chownr@1.1.4
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ commander@6.0.0
├─ concat-map@0.0.1
├─ debug@4.1.1
├─ devtools-protocol@0.0.781568
├─ end-of-stream@1.4.4
├─ extract-zip@2.0.1
├─ fd-slicer@1.1.0
├─ find-up@4.1.0
├─ fs-constants@1.0.0
├─ fs.realpath@1.0.0
├─ get-stream@5.2.0
├─ glob@7.1.6
├─ has-flag@4.0.0
├─ https-proxy-agent@4.0.0
├─ ieee754@1.1.13
├─ inflight@1.0.6
├─ locate-path@5.0.0
├─ mime@2.4.6
├─ minimatch@3.0.4
├─ mkdirp-classic@0.5.3
├─ ms@2.1.2
├─ once@1.4.0
├─ p-limit@2.3.0
├─ p-locate@4.1.0
├─ p-try@2.2.0
├─ path-exists@4.0.0
├─ path-is-absolute@1.0.1
├─ pend@1.2.0
├─ pkg-dir@4.2.0
├─ progress@2.0.3
├─ proxy-from-env@1.1.0
├─ puppeteer@5.2.1
├─ readable-stream@3.6.0
├─ rimraf@3.0.2
├─ safe-buffer@5.2.1
├─ string_decoder@1.3.0
├─ supports-color@7.1.0
├─ tar-fs@2.1.0
├─ tar-stream@2.1.3
├─ through@2.3.8
├─ unbzip2-stream@1.4.3
├─ util-deprecate@1.0.2
├─ ws@7.3.1
└─ yauzl@2.10.0
Done in 3.13s.

```

**Comment by MindaugasLaganeckas** [comment]
I just tried with the docker image, where we install the newly released mermaid cli and it worked fine:
``docker run minlag/mermaid-cli:8.7.0 -h``
I will try to reproduce the error by installing locally. ETA: sometime next week.

**Comment by MindaugasLaganeckas** [comment]
@vkotovv : I cannot reproduce the error:
```
root@f49fbe021825:/# yarn add @mermaid-js/mermaid-cli
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 60 new dependencies.
info Direct dependencies
└─ @mermaid-js/mermaid-cli@8.7.0
info All dependencies
├─ @mermaid-js/mermaid-cli@8.7.0
├─ @types/color-name@1.1.1
├─ @types/node@14.0.27
├─ @types/yauzl@2.9.1
├─ agent-base@5.1.1
├─ ansi-styles@4.2.1
├─ balanced-match@1.0.0
├─ base64-js@1.3.1
├─ bl@4.0.2
├─ brace-expansion@1.1.11
├─ buffer-crc32@0.2.13
├─ buffer@5.6.0
├─ chalk@4.1.0
├─ chownr@1.1.4
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ commander@6.0.0
├─ concat-map@0.0.1
├─ debug@4.1.1
├─ devtools-protocol@0.0.781568
├─ end-of-stream@1.4.4
├─ extract-zip@2.0.1
├─ fd-slicer@1.1.0
├─ find-up@4.1.0
├─ fs-constants@1.0.0
├─ fs.realpath@1.0.0
├─ get-stream@5.2.0
├─ glob@7.1.6
├─ has-flag@4.0.0
├─ https-proxy-agent@4.0.0
├─ ieee754@1.1.13
├─ inflight@1.0.6
├─ locate-path@5.0.0
├─ mime@2.4.6
├─ minimatch@3.0.4
├─ mkdirp-classic@0.5.3
├─ ms@2.1.2
├─ once@1.4.0
├─ p-limit@2.3.0
├─ p-locate@4.1.0
├─ p-try@2.2.0
├─ path-exists@4.0.0
├─ path-is-absolute@1.0.1
├─ pend@1.2.0
├─ pkg-dir@4.2.0
├─ progress@2.0.3
├─ proxy-from-env@1.1.0
├─ puppeteer@5.2.1
├─ readable-stream@3.6.0
├─ rimraf@3.0.2
├─ safe-buffer@5.2.1
├─ string_decoder@1.3.0
├─ supports-color@7.1.0
├─ tar-fs@2.1.0
├─ tar-stream@2.1.3
├─ through@2.3.8
├─ unbzip2-stream@1.4.3
├─ util-deprecate@1.0.2
├─ ws@7.3.1
└─ yauzl@2.10.0
Done in 11.92s.
root@f49fbe021825:/# ./node_modules/.bin/mmdc -h
Usage: mmdc [options]

Options:
  -V, --version                                   output the version number
  -t, --theme [theme]                             Theme of the chart, could be default, forest, dark or neutral. Optional. Default: default (default: "default")
  -w, --width [width]                             Width of the page. Optional. Default: 800 (default: "800")
  -H, --height [height]                           Height of the page. Optional. Default: 600 (default: "600")
  -i, --input <input>                             Input mermaid file. Required.
  -o, --output [output]                           Output file. It should be either svg, png or pdf. Optional. Default: input + ".svg"
  -b, --backgroundColor [backgroundColor]         Background color. Example: transparent, red, '#F0F0F0'. Optional. Default: white
  -c, --configFile [configFile]                   JSON configuration file for mermaid. Optional
  -C, --cssFile [cssFile]                         CSS file for the page. Optional
  -s, --scale [scale]                             Puppeteer scale factor, default 1. Optional
  -p --puppeteerConfigFile [puppeteerConfigFile]  JSON configuration file for puppeteer. Optional
  -h, --help                                      display help for command
```

**Comment by vkotovv** [comment]
I've tried to use npm to install it for the first time, it gave me this error:
```
kotov@kotov-office:~/Apps/mermaid-cli$ npm install @mermaid-js/mermaid-cli

> puppeteer@5.2.1 install /home/kotov/Apps/mermaid-cli/node_modules/puppeteer
> node install.js

(node:21308) UnhandledPromiseRejectionWarning: /home/kotov/Apps/mermaid-cli/node_modules/puppeteer/lib/cjs/puppeteer/install.js:134
                    catch {
                          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at download (/home/kotov/Apps/mermaid-cli/node_modules/puppeteer/install.js:35:7)
(node:21308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN saveError ENOENT: no such file or directory, open '/home/kotov/Apps/mermaid-cli/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/kotov/Apps/mermaid-cli/package.json'
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN mermaid-cli No description
npm WARN mermaid-cli No repository field.
npm WARN mermaid-cli No README data
npm WARN mermaid-cli No license field.

+ @mermaid-js/mermaid-cli@8.7.0
added 63 packages from 77 contributors and audited 63 packages in 5.191s
found 0 vulnerabilities

```

After that I've deleted `node_modules` and installed it via `yarn`, and now I have the error in the description.
Is there anything wrong with my system now? Maybe I should uninstall something or delete some files to make it work?

**Comment by MindaugasLaganeckas** [comment]
@vkotovv : I would suggest to upgrade yarn if you are not using the newest. Another thing, you can try to use ```node``` docker image for your experiments. This way you can try to compare your system setup with the one in the docker image. I hope this helps!

**Comment by vkotovv** [comment]
Still the same error after upgrading yarn to 1.22.4.

**Comment by bhyland** [comment]
I can confirm this error using npm 6.14.8 on Ubuntu 18.04
