### ISSUE TITLE
Failing to generate an image from the state diagram

### ISSUE THREAD

**Issue by diegobernardes** [mermaid-js/mermaid-cli#4]
This is the error:
```
mmdc -i diagram.mmd -o diagram.png
(node:92883) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 1:
stateDiagram	s1: In
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/dbernardes/.asdf/installs/nodejs/13.8.0/.npm/lib/node_modules/mermaid.cli/index.bundle.js:4:361
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:92883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The mermaid file:
```
stateDiagram
	s1: Input Queue
	s2: Function
	s3: Function Success
	s4: Function Fail
	s5: Notification Queue
	s6: Notification Queue Success
	s7: Notification Queue Fail

	[*] --> s1
	s1 --> s2
	s2 --> s3
	s2 --> s4
	s3 --> s5
	s4 --> s5
	s5 --> s6
	s5 --> s7
	s6 --> [*]
	s7 --> s1
```

But it's working fine at the [web editor](https://mermaid-js.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic3RhdGVEaWFncmFtXG5cdHMxOiBJbnB1dCBRdWV1ZVxuXHRzMjogRnVuY3Rpb25cblx0czM6IEZ1bmN0aW9uIFN1Y2Nlc3Ncblx0czQ6IEZ1bmN0aW9uIEZhaWxcblx0czU6IE5vdGlmaWNhdGlvbiBRdWV1ZVxuXHRzNjogTm90aWZpY2F0aW9uIFF1ZXVlIFN1Y2Nlc3Ncblx0czc6IE5vdGlmaWNhdGlvbiBRdWV1ZSBGYWlsXG5cblx0WypdIC0tPiBzMVxuXHRzMSAtLT4gczJcblx0czIgLS0-IHMzXG5cdHMyIC0tPiBzNFxuXHRzMyAtLT4gczVcblx0czQgLS0-IHM1XG5cdHM1IC0tPiBzNlxuXHRzNSAtLT4gczdcblx0czYgLS0-IFsqXVxuXHRzNyAtLT4gczEiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ):
![image](https://user-images.githubusercontent.com/14483/82459201-8afcd080-9aaf-11ea-89f8-3b87439410a9.png)

**Comment by LarryBattle** [comment]
I just tested out your file on `"@mermaid-js/mermaid-cli": "^8.5.1-2"` on Ubuntu and it generated the correct diagram without any errors.
 
The error in the stacktrace (`stateDiagram	s1: In`) looks like `mermaid-cli` as unable to read your line breaks in the file.
Try recreating `diagram.mmd` in an different text editor on the same system.

**Comment by diegobernardes** [comment]
Still giving me an error. There is no hidden char at the file, look at the editor showing all the chars.

![image](https://user-images.githubusercontent.com/14483/84059155-087e7700-a9b2-11ea-9666-43b448ff5781.png)

**Comment by MindaugasLaganeckas** [comment]
Hey @diegobernardes, I have tried to reproduce the error you have reported without any luck. From the error message it seems clear, that there is something wrong with your input file. Anyhow, I have created a branch for your case. You can find your state file here: https://github.com/MindaugasLaganeckas/mermaid-cli/blob/issue/4/test/issue-4.mmd and the diagram, generated by mermaid-cli, here: https://github.com/MindaugasLaganeckas/mermaid-cli/suites/844280879/artifacts/9556201. The filename to look for is issue-4.mmd.svg.

**Comment by tuang3142** [comment]
Hi @MindaugasLaganeckas, I ran into a similar situation the other day where I could not render some graphs to images.
This is the graph.
```
graph TD;
  client--internet-->cloudflare-->aws_balancer-->haproxy_container-->frontend_container
  haproxy_container-->backend_container
  subgraph "convox"
    haproxy_container
    frontend_container
    backend_container
  end
```
 I installed mermaid-cli on a Linux docker via `yarn`. Running
`./node_modules/.bin/mmdc -p puppeteer-config.json -i input.mmd -o output.png` showed this error:
```
(node:596) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 2:
...nternet-->cloudflare-->aws_balancer-->ha
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'EOF', got 'ARROW_POINT'
```
However, when the cli is installed with `npm` the problem disappeared. 
It would be great if you can take a look at this.

**Comment by Kochise** [comment]
Got this (see attached picture)

![state](https://user-images.githubusercontent.com/23077417/98947803-f4591b80-24f5-11eb-9e53-fa3cfebaf01a.png)

Check this : https://github.com/mermaid-js/mermaid/issues/1235

The old repo (v0.5.1) is not functional, use the new repo (v8.+). It's confusing, but 'mermaidjs' is not the same as 'mermaid-js'.

npm install -g mermaid.cli ---> fails (v0.5.1)
npm install -g @mermaid-js/mermaid-cli ---> works (v8.+)

**Comment by MindaugasLaganeckas** [comment]
Cannot reproduce. No answer from the reporter.

**Comment by yannicschroeer** [comment]
I was able to reproduce this by using Node v16. Using Node v18 resolved this issue for me.
