### ISSUE TITLE
autonumber doesn't seem to work

### ISSUE THREAD

**Issue by ddurham** [mermaid-js/mermaid-cli#40]
Trying to render a sequence diagram with autonumber.

----
sequenceDiagram
    autonumber
    Caller->>+Receiver:Invoke
----

Throws this error:

```
(node:13159) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 2:
...agram    autonumber    Caller->>+Recei
----------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', got 'NL'
    at x.parseError (file:///usr/local/lib/node_modules/mermaid.cli/mermaid.min.js:1:423219)
    at x.parse (file:///usr/local/lib/node_modules/mermaid.cli/mermaid.min.js:1:424385)
    at Object.e.draw (file:///usr/local/lib/node_modules/mermaid.cli/mermaid.min.js:1:720085)
    at Object.render (file:///usr/local/lib/node_modules/mermaid.cli/mermaid.min.js:1:760928)
    at s (file:///usr/local/lib/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///usr/local/lib/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/usr/local/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

 version: '8.7.0',

**Comment by MindaugasLaganeckas** [comment]
@ddurham : please, follow our isssue template when reporting bugs.

**Comment by grangerjs** [comment]
I'm also seeing this issue when running `mmdc -i account-statement-token.mmd -o account-statement-token.png -c config.json`. If I remove `autonumber` from `account-statement-token.mmd` with no other changes, the diagram is successfully generated.

### account-statement-token.mmd
```
sequenceDiagram
  autonumber
  title: GET /account-statement-token/:accountId
  participant C as client
  participant R as router
  participant S as validation/serialization
  participant H as handler
  participant A as inner-api auth
  participant I as inner-api
  C ->> R: GET /account-statement-token/:accountId
  R ->> S: validate params
  S ->> H: params validated
  H ->> A: request auth token
  A -->> H: auth token returned
  H ->> I: request statement token
  I -->> S: statement token returned
  S -->> C: 200 - OK
  Note over S: serialize response
```

### config.json
``` json
{
  "logLevel": 0,
  "sequence": { "actorMargin": 50, "showSequenceNumbers": true }
}
```

### error output
``` bash
❯ mmdc -i account-statement-token.mmd -o account-statement-token.png -c config.json
(node:19175) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 2:
...Diagram  autonumber  title: GET /accou
----------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', got 'NL'
    at x.parseError (file:///Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/mermaid.min.js:1:423219)
    at x.parse (file:///Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/mermaid.min.js:1:424385)
    at Object.e.draw (file:///Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/mermaid.min.js:1:720085)
    at Object.render (file:///Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/mermaid.min.js:1:760928)
    at s (file:///Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/jeremygranger/.nvm/versions/node/v12.16.2/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
```

When `autonumber` is removed from the `.mmd` file, this is the output:
![image](https://user-images.githubusercontent.com/42156515/91896012-6e973500-ec55-11ea-88cf-89f4982ca7a5.png)

**Comment by MindaugasLaganeckas** [comment]
@grangerjs : thank you for a thorough problem description. Unfortunately, based on your input, I think this issue should be forwarded to the mermaid core team. CLI is a very thin client calling mermaid core. We do not handle such details as autonumbers.

**Comment by grangerjs** [comment]
@MindaugasLaganeckas okay, sounds good. Thanks so much for the feedback!

**Comment by MindaugasLaganeckas** [comment]
@grangerjs : can we close this issue?
