### ISSUE TITLE
Compile error in index.js?

### ISSUE THREAD

**Issue by jrynd** [mermaid-js/mermaid-cli#442]
I am using node 19 (installed with nvm)
When I try to use mermaid-cli, I get:

```~/.nvm/versions/node/v19.0.1/lib/node_modules/@mermaid-js/mermaid-cli/src/cli.js:3
import { cli, error } from './index.js'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Is Mermaid incompatible with Node 19? If so what version is required?

**Comment by aloisklink** [comment]
Mermaid-cli should be compatible with Node v19! I just tested it, and it seemed to work.

Could you try running the following:

```bash
npx @mermaid-js/mermaid-cli@latest --help
```

`npx` comes bundled with `npm` version 5.2+ (aka most recent versions of Node), and will automatically download and cache `@mermaid-js/mermaid-cli` in a global location so you can use it anywhere on your system.

You should get the following as your output (please be aware, installing will take a while, since [puppeteer](https://github.com/puppeteer/puppeteer) will download a version of Chromium for rendering):

```console
user@my-pc:~$ npx @mermaid-js/mermaid-cli@latest --help
Need to install the following packages:
  @mermaid-js/mermaid-cli@9.2.2
Ok to proceed? (y) y
Usage: mmdc [options]

Options:
  -V, --version                                   output the version number
  -t, --theme [theme]                             Theme of the chart, could be default, forest, dark or neutral. Optional.
                                                  Default: default (default: "default")
  -w, --width [width]                             Width of the page. Optional. Default: 800 (default: "800")
  -H, --height [height]                           Height of the page. Optional. Default: 600 (default: "600")
  -i, --input <input>                             Input mermaid file. Files ending in .md will be treated as Markdown and all
                                                  charts (e.g. ```mermaid (...)```) will be extracted and generated. Required.
  -o, --output [output]                           Output file. It should be either md, svg, png or pdf. Optional. Default:
                                                  input + ".svg"
  -e, --outputFormat <format>                     Output format for the generated image. It should be either svg, png or pdf.
                                                  Optional. Default: output file extension
  -b, --backgroundColor [backgroundColor]         Background color for pngs/svgs (not pdfs). Example: transparent, red,
                                                  '#F0F0F0'. Optional. Default: white
  -c, --configFile [configFile]                   JSON configuration file for mermaid. Optional
  -C, --cssFile [cssFile]                         CSS file for the page. Optional
  -s, --scale [scale]                             Puppeteer scale factor, default 1. Optional
  -f, --pdfFit [pdfFit]                           Scale PDF to fit chart
  -q, --quiet                                     Suppress log output
  -p --puppeteerConfigFile [puppeteerConfigFile]  JSON configuration file for puppeteer. Optional
  -h, --help                                      display help for command
```

If it doesn't work, please also post your operating system. Most developers use Unix-based systems, so it means Windows is often less tested.

**Comment by jrynd** [comment]
This was apparently invalid; I tried it again and it worked.
