### ISSUE TITLE
Could not find Chromium (rev. 1108766)

### ISSUE THREAD

**Issue by raffaem** [mermaid-js/mermaid-cli#671]
**Describe the bug**

Install with:
```
sudo npm install -g @mermaid-js/mermaid-cli
```

Create `input.mmd` as:
```
flowchart LR
  A-->B
```

Launch 
```
mmdc -i input.mmd -o input.png
```

Get
```
➜  mmdc -i input.mmd -o input.png

Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/raffaele/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at async ChromeLauncher.launch (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
    at async run (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:404:19)
    at async cli (file:///usr/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:184:3)

[ble: exit 1]
```

Same error as #650, but I don't have a "mermaid" software as [described in the workaround that that OP used](https://github.com/mermaid-js/mermaid-cli/issues/650#issuecomment-1953200767)

**To Reproduce**

See above

**Expected behavior**

Should produce PNG file.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Arch Linux
- Browser [e.g. chrome, safari] Firefox and Chromium

**Comment by raffaem** [comment]
Downgrading to 9.1.7 with:
```
sudo npm install -g @mermaid-js/mermaid-cli@9.1.7
```
makes mmdc work again.

**Comment by saiwing-yeung** [comment]
Same issue for me. Downgrading to 9.1.7 also worked.

**Comment by raffaem** [comment]
Still same issue. @mermaid-js any ideas?

**Comment by aloisklink** [comment]
> Still same issue. https://github.com/mermaid-js any ideas?

If you run `npm install @mermaid-js/mermaid-cli` (without `sudo`) are there any errors shown?

> [!Note]
>
> Running `npm install @mermaid-js/mermaid-cli` without the `-g` flag will install it only in the current folder.

[Puppeteer v19.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v19.0.0) now downloads Chromium into the `~/.cache/puppeteer` folder by default. It's possible that this folder cannot be written/loaded from (e.g. if you used `sudo`, and that folder is now locked to the admin user only).

Deleting the `~/.cache/puppeteer` folder and rerunning `npm install @mermaid-js/mermaid-cli` might help!

You can also try reading https://pptr.dev/troubleshooting#could-not-find-expected-browser-locally to download puppeteer into a different folder using `PUPPETEER_CACHE_DIR=~/my-folder-to-download-puppeteer-to`cd

**Comment by hamad12a** [comment]
I need to convert markdown mermaid with latex expressions, so only the recent version supports latex

**Comment by terra-nova** [comment]
> I need to convert a markdown mermaid file contains latex expressions, so only the recent version supports latex. I keep receiving `Error: Could not find Chromium (rev. 1108766).`

The cause of the error seems to be that that specific revision is no longer available at Google (HTTP status code 404):

```
npm error ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm error Error: Download failed: server returned code 404. URL: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1108766/chrome-linux.zip
```

**Comment by MindaugasLaganeckas** [comment]
If you hit this link from your browser  https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1108766/chrome-linux.zip then you see that the file is there. Just tried it seconds ago.

**Comment by terra-nova** [comment]
> If you hit this link from your browser https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1108766/chrome-linux.zip then you see that the file is there. Just tried it seconds ago.

Yes, you are right. I fell victim to an issue in Pupeteer when running behind a HTTP proxy (https://github.com/puppeteer/puppeteer/issues/10575).

**Comment by aloisklink** [comment]
One thing that may also help is running `npm -g rebuild puppeteer` if you've installed `@mermaid-js/mermaid-cli` with the `-g` flag, or `npm rebuild puppeteer` if you've installed it without the `-g` flag.

That should tell puppeteer to redownload the chrome browser!

**Comment by ezYakaEagle442** [comment]
I hit exactly the same error on WSL2 / Ubuntu 2404, unfortunately the workaround suggested did not fix the issue.
See [https://github.com/puppeteer/puppeteer/issues/14798](https://github.com/puppeteer/puppeteer/issues/14798)

**Comment by qw3ry** [comment]
This error also happens with GitHub Actions.

<details><summary>
Downgrading to 9.1.7 gives a different error (expand to see more)</summary>
Probably 9.1.7 is too old
<code>
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work.
    at Timeout.onTimeout (file:///opt/hostedtoolcache/node/26.3.0/x64/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:280:20)
    at listOnTimeout (node:internal/timers:605:17)
    at process.processTimers (node:internal/timers:541:7)
    at genericNodeError (node:internal/errors:998:15)
    at wrappedFn (node:internal/errors:543:14)
    at ChildProcess.exithandler (node:child_process:417:12)
    at ChildProcess.emit (node:events:509:20)
    at maybeClose (node:internal/child_process:1108:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'mmdc -i image-sources/diagrams/user-journeys/journey-adding-product.mmd -o static/renderedDiagrams/journey-adding-product-light.svg '
}
</code>
</details>
Full GitHub Action log here: <a href="https://github.com/qw3ry/misarch-docs/actions/runs/26884409555/job/79292587639">https://github.com/qw3ry/misarch-docs/actions/runs/26884409555/job/79292587639</a>

I tried various other things, like local install or running with npx, but nothing really worked

**Comment by ldesousa** [comment]
This error is present with version 11.16.0 on Debian Trixie.

**Comment by qw3ry** [comment]
There seems to be an [issue with `puppeteer` and npm 26](https://github.com/puppeteer/puppeteer/issues/14957). I could resolve the issue by downgrading my GitHub Action runner to `25.15.x`
