### ISSUE TITLE
Docker image failure

### ISSUE THREAD

**Issue by AlexisBRENON** [mermaid-js/mermaid-cli#762]
**Describe the bug**
With the newest versions of the docker image, I'm not able to render my chart anymore.
The process hangs for a while and finally crash with the following error:
```
ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
    at new Callback (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
    at CallbackRegistry.create (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
    at Connection._rawSend (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:26)
    at CdpCDPSession.send (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
    at NetworkManager.addClient (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/NetworkManager.js:59:20)
    at FrameManager.initialize (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:1[67](https://github.com/greenbids/greenbids-tailor-external/actions/runs/11270373229/job/31340948174#step:4:68):38)
    at #initialize (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:280:36)
    at CdpPage._create (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:93:31)
    at file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Target.js:202:32
```

**To Reproduce**

1. Create a file `test.mmd`:
  ```text
  sequenceDiagram
      A ->>+ B: hello
      B -->>- A: ""
  ```

2. Render the chart with **old** docker image:
  ```bash
  docker run --rm -u $(id -u) -v $PWD:/data ghcr.io/mermaid-js/mermaid-cli/mermaid-cli:11.2.1-beta.3 -i /data/test.mmd
  ```

3. Render the chart with **new** docker image:
  ```bash
  docker run --rm -u $(id -u) -v $PWD:/data ghcr.io/mermaid-js/mermaid-cli/mermaid-cli:11.2.1 -i /data/test.mmd
  ```

**Expected behavior**
I expected the rendering to succeed as previously.

**Additional context**
You may see more examples in my repository which uses the image as part of the CI.
* [New failing job](https://github.com/greenbids/greenbids-tailor-external/actions/runs/11270373229/job/31340948174)
* [Old successful job](https://github.com/greenbids/greenbids-tailor-external/actions/runs/11016419877/job/30591893342)

**Comment by aloisklink** [comment]
I can't replicate this issue on my local machine using:

```bash
cat test-positive/flowchart1.mmd | docker run --rm -i ghcr.io/mermaid-js/mermaid-cli/mermaid-cli:11.2.1 --input - --output - --outputFormat svg
```

**However, I have replicated this using GitHub Codespaces** (which I believe uses similar machines to the default GitHub Actions runners), **and I'm having the same issue.** `ghcr.io/mermaid-js/mermaid-cli/mermaid-cli:11.2.1` doesn't work, but `ghcr.io/mermaid-js/mermaid-cli/mermaid-cli:11.2.1-beta.5` works.

![image](https://github.com/user-attachments/assets/da0604ee-a0fb-4e89-b1c3-d9c71579e6e8)
