### ISSUE TITLE
Docker mmdc times out on github actions after version 12?

### ISSUE THREAD

**Issue by flammie** [mermaid-js/mermaid-cli#763]
**Describe the bug**

We use the mmdc and the docker to generate mermaid diagrams on github pages: https://github.com/divvun/compile-mermaid-markdown-action, this has started failing since few days, downgrading the docker version fixes the problem but there's probably some configuration fix or similar that works for longer term?

**To Reproduce**

1. Use https://github.com/divvun/compile-mermaid-markdown-action revision c6e8e46de10fb19c8200b8cf2dece818bae39147 in a github action
2. (e.g. try our github pages at https://github.com/giellalt/giellalt.github.io/)
3. The github action will time out when trying to generated the diagram

**Expected behavior**

The generation should go through

**Screenshots**

Here's a log from failed generation:

https://github.com/giellalt/giellalt.github.io/actions/runs/11215090759/job/31171552078#step:9:124

the main issue seems to be:

```
 + /home/mermaidcli/node_modules/.bin/mmdc -p /puppeteer-config.json -i mermaid-svgs/tmp/mermaid-block-1 -o mermaid-svgs/-_infra_MarkdownTestReference-md-1.svg
Generating single mermaid chart

ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at <instance_members_initializer> (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
    at new Callback (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
    at CallbackRegistry.create (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
    at Connection._rawSend (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:86:26)
    at CdpCDPSession.send (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
    at NetworkManager.addClient (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/NetworkManager.js:59:20)
    at FrameManager.initialize (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:167:38)
    at #initialize (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:280:36)
    at CdpPage._create (file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:93:31)
    at file:///home/mermaidcli/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Target.js:202:32
```

Here's one log after fixing the docker version: https://github.com/giellalt/giellalt.github.io/actions/runs/11256543303/job/31298683778

HEre's the fix: https://github.com/divvun/compile-mermaid-markdown-action/commit/1d345f4326efe52562468b0b111c5debca631afa

**Desktop (please complete the following information):**

Whatever Github Actions has

**Additional context**

**Comment by aloisklink** [comment]
Duplicate of #762
